repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.247
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        stages: [manual]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
        stages: [manual]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --quiet
        files: ^(sunweg/.+)?[^/]+\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle==2.10.0
          - pyflakes==3.0.1
          - flake8-docstrings==1.6.0
          - pydocstyle==6.2.3
          - flake8-comprehensions==3.10.1
          - flake8-noqa==1.3.0
          - mccabe==0.7.0
        stages: [manual]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=sunweg/tests/bandit.yaml
        files: ^sunweg/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode)
      - id: no-commit-to-branch
        args:
          - --branch=main
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.5.0
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      # pre-commit run --hook-stage manual python-typing-update --all-files
      - id: python-typing-update
        stages: [manual]
        args:
          - --py310-plus
          - --force
          - --keep-updates
        files: ^sunweg/.+\.py$
  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      - id: mypy
        name: mypy
        entry: mypy
        language: script
        types: [python]
        require_serial: true
        files: ^sunweg/.+\.py$
      - id: pylint
        name: pylint
        entry: pylint -j 0 --ignore-missing-annotations=y
        language: script
        types: [python]
        files: ^sunweg/.+\.py$
